### ISSUE TITLE
run-gator: fails after trying to browse to a domain's collected page

### ISSUE THREAD

**Issue by groovecoder** [mdn/webalyzer#13]
Steps to reproduce:
1. Run webalyzer locally via the [updated README instructions](https://github.com/mdn/webalyzer/blob/master/README.md)
2. Collect some pages from a domain
3. Go to the domain's "collected" view: http://127.0.0.1:8000/collected/example.com

Expected results:
Should see a screen-shot of the page

Actual results:
`run-gator` process throws a stacktrace:

```
Generating screenshot for 7
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/lcrouch/code/webalyzer/webalyzer/base/management/commands/run-gator.py", line 14, in handle
    worker.run_forever()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/alligator/workers.py", line 99, in run_forever
    result = self.gator.pop()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/alligator/gator.py", line 145, in pop
    return self.execute(task)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/alligator/gator.py", line 215, in execute
    return task.run()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/alligator/tasks.py", line 250, in run
    result = self.func(*self.func_args, **self.func_kwargs)
  File "/Users/lcrouch/code/webalyzer/webalyzer/collected/views.py", line 208, in generate_screenshot
    stderr=subprocess.PIPE
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by peterbe** [comment]
The `collected` app was maybe a bad idea. Or at least the form I whipped it up. It doesn't make sense to draw thumbnails of thousands and thousands of HTML blobs. 
There shouldn't be any individualism with the collected HTML blobs. It should ideally always be treated as sequences or collections. E.g. "You have 2,367 collected HTML documents" as opposed to "Here is a list of your 2,367 collected HTML documents". 

By the way, I'm guessing the error at hand is related to a lack of phantomjs installed. The error message would need some love and the README might need some love. Either way, I would just consider abandoning this app for a while.
